// Login
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// Setting
export const OFF_SETTING_WIFI_ONLY = 'OFF_SETTING_WIFI_ONLY';
export const OFF_SETTING_RETRY_CONNECTION = 'OFF_SETTING_RETRY_CONNECTION';
export const ON_SETTING_WIFI_ONLY = 'ON_SETTING_WIFI_ONLY';
export const ON_SETTING_RETRY_CONNECTION = 'ON_SETTING_RETRY_CONNECTION';
